_core:
  default_config_hash: wB2h-QBawANCiCVEXy6bJjiDfvZY6EONZ6-wRB_RYQc
langcode: fr
hotlink: false
origin: 'https://boutique.akikofairtrade.com'
origin_dir: sites/default/files
proxy_headers: ''
use_imagecache_root: true
verify: true
excluded_extensions: ''
